### ISSUE TITLE
in fact,the dynamic relu is well?who try to use it ?

### ISSUE THREAD

**Issue by daixiangzi** [Islanna/DynamicReLU#3]

**Comment by QiushiYang** [comment]
I tried to use it on a unet-based medical image segmentation task but found the performance dropped :-(

**Comment by QiushiYang** [comment]
I tried to use it on a unet-based medical image segmentation task but found the performance dropped :-(  Do not know the reason yet.

**Comment by daixiangzi** [comment]
> I tried to use it on a unet-based medical image segmentation task but found the performance dropped :-( Do not know the reason yet.

ha ha,我在知乎看到有人说对比resnet50,下降了一点

**Comment by SudongCAI** [comment]
Yes, I tried this code... But the performance met a clear drop on CIFAR-100 (with ResNets of different layer-depths). 
That's so wired...
